const chicken = [
    {id:1,
     name:"Cheesy Chicken Alfredo Pasta Bake",
     img:"pic/chicken/one.jpg",
     cooker:"Spencer Kombol",
     Ingredients:[ "<h5 class='animated fadeInDown'>for 6 servings</h5><br/>",
                   "<h6 class='animated fadeInLeft'>1 tablespoon olive oil</h6><br/>",
                   "<h6 class='animated fadeInLeft'>3 chicken breasts, cubed</h6><br/>",
                   "<h6 class='animated fadeInLeft'>salt, to taste</h6><br/>",
                   "<h6 class='animated fadeInLeft'>pepper, to taste</h6><br/>",
                   "<h6 class='animated fadeInLeft'>4 cloves garlic, minced</h6><br/>",
                   "<h6 class='animated fadeInLeft'>2 ½ cups chicken broth (590 mL)</h6><br/>",
                   "<h6 class='animated fadeInLeft'>1 lb penne pasta (450 g), uncooked</h6><br/>",
                   "<h6 class='animated fadeInLeft'>2 cups parmesan cheese (220 g)</h6><br/>",
                   "<h6 class='animated fadeInLeft'>2 cups mozzarella cheese (230 g)</h6><br/>",
                   "<h6 class='animated fadeInLeft'>1 handful fresh parsley, chopped</h6><br/>"],
     Preparation:[
                   "<li class='animated fadeInLeft'>In a pot, heat oil and add chicken.</li><br/>",
                   "<li class='animated fadeInLeft'>Season chicken with salt and pepper.</li><br/>",
                   "<li class='animated fadeInLeft'>Add garlic, then brown the chicken.</li><br/>",
                   "<li class='animated fadeInLeft'>Add broth, heavy cream, and pasta, and bring to a boil.</li><br/>",
                   "<li class='animated fadeInLeft'>Cover and reduce the heat to a simmer for 15-20 min.</li><br/>",
                   "<li class='animated fadeInLeft'>Turn off heat and stir in 1 ½ cups (165 grams) of parmesan cheese.</li><br/>",
                   "<li class='animated fadeInLeft'>Pour half of the pasta into a greased 11×7 inch or 9×13 inch (28x18 cm or 33x23 cm) baking dish.</li><br/>",
                   "<li class='animated fadeInLeft'>Sprinkle evenly with 1 cup (115 grams) of mozzarella cheese.</li><br/>",
                   "<li class='animated fadeInLeft'>Layer the remaining half of the pasta evenly on top. Sprinkle evenly with 1 cup of mozzarella (115 grams) and ½ cup (55 grams) of parmesan.</li><br/>",
                   "<li class='animated fadeInLeft'>Broil 10 - 15 minutes, or until the cheese is golden brown. Remove and sprinkle with fresh parsley.</li><br/>",
                   "<li class='animated fadeInLeft'>Serve warm and enjoy!</li><br/>",
                  ]
},
   {id:2,
       name:"Easy Chicken Enchiladas",
       img:"pic/chicken/2chicken.jpeg",
       cooker:"Amreen Khureshi",
       Ingredients:[ "<h6 class='animated fadeInDown'>for 5 serving</h6><br/>",
                     "<h6 class='animated fadeInLeft'>1 cup shredded chicken (100 g)</h6><br/>",
                     "<h6 class='animated fadeInLeft'>¼ cup corn (40 g)</h6><br/>",
                     "<h6 class='animated fadeInLeft'>½ cup shredded cheese (50 g)</h6><br/>",
                     "<h6 class='animated fadeInLeft'>1 can enchilada sauce, 19 ounces (535 grams)</h6><br/>",
                      "<h6 class='animated fadeInLeft'>5 tortillas</h6><br/>",
                      ],
       Preparation:[
                     "<li class='animated fadeInLeft'>Heat the oven to 350°F (180°C).</li><br/>",
                     "<li class='animated fadeInLeft'>Combine the chicken, corn, enchilada sauce (leave ¼ cup for topping and base), and ¼ cup (25 G) cheese in a bowl.</li><br/>",
                     "<li class='animated fadeInLeft'>Pour thin layer of enchilada sauce into a pan.</li><br/>",
                     "<li class='animated fadeInLeft'>Pour thin layer of enchilada sauce onto a plate.</li><br/>",
                     "<li class='animated fadeInLeft'>Dip a tortilla in the plate with enchilada sauce until soaked. Fill with chicken mixture and roll. Place in the pan.</li><br/>",
                     "<li class='animated fadeInLeft'>Top completed enchiladas with the remaining enchilada sauce and cheese.</li><br/>",
                     "<li class='animated fadeInLeft'>Bake for 15 minutes, or until cheese has melted.</li><br/>",
                     "<li class='animated fadeInLeft'>Enjoy!</li><br/>",
                     ]
},
   {id:3,
       name:"Jerk Chicken And Pineapple Skewers",
       img:"pic/chicken/3chicken.jpeg",
       cooker:"Alix Traeger & Ali Clarke",
       Ingredients:[  "<h6 class='animated fadeInDown'>for 4 servings</h6><br/>",
                      "<h6 class='animated fadeInLeft'>7 scallions, cut into 2 in (5 cm) pieces</h6><br/>",
                      "<h6 class='animated fadeInLeft'>3 habanero peppers, seeded</h6><br/>",
                      "<h6 class='animated fadeInLeft'>8 cloves garlic</h6><br/>",
                      "<h6 class='animated fadeInLeft'>1 fresh ginger, peeled and thinly sliced</h6><br/>",
                      "<h6 class='animated fadeInLeft'>⅓ cup dark brown sugar (75 g), tightly packed</h6><br/>",
                      "<h6 class='animated fadeInLeft'>2 tablespoons soy sauce</h6><br/>",
                      "<h6 class='animated fadeInLeft'>1 tablespoon ground allspice</h6><br/>",
                      "<h6 class='animated fadeInLeft'>1 teaspoon cinnamon</h6><br/>",
                      "<h6 class='animated fadeInLeft'>1 tablespoon dried thyme</h6><br/>",
                      "<h6 class='animated fadeInLeft'>1 ½ lb boneless, skinless chicken breast (680 g), cut into 1 1/2 in (3 cm) pieces</h6><br/>",
                      "<h6 class='animated fadeInLeft'>8 oz pineapple juice (240 mL)</h6><br/>",
                      "<h6 class='animated fadeInLeft'>¼ cup ketchup (60 g), plus 2 tablespoons of ketchup</h6><br/>",
                      "<h6 class='animated fadeInLeft'>kosher salt, to taste</h6><br/>",
                      "<h6 class='animated fadeInLeft'>1 large red onion, cut into 1 1/2 in (3 cm) pieces</h6><br/>",
                      "<h6 class='animated fadeInLeft'>2 red bell peppers, cut into 1 1/2 in (3 cm) pieces</h6><br/>",
                      "<h6 class='animated fadeInLeft'>2 cups pineapple (490 g), cut into 1 1/2 in (3 cm) cubes</h6><br/>",
                      "<h6 class='animated fadeInLeft'>lime wedge, for serving</h6><br/>",
                      "<h6 class='animated fadeInLeft'>¼ cup fresh cilantro (10 g), finely chopped, for garnish</h6><br/>",
                      ],
       Preparation:[
                    "<li class='animated fadeInLeft'>Preheat the oven to 375ºF (190ºC). Line 2 baking sheets with parchment paper.</li><br/>",
                     "<li class='animated fadeInLeft'>In a food processor, combine the scallions, habanero peppers, garlic, ginger, brown sugar, soy sauce, allspice, cinnamon, and thyme. Puree until broken down into a into a thick paste, about 1 minute.</li><br/>",
                     "<li class='animated fadeInLeft'>In a medium bowl, toss the chicken with 2-4 tablespoons of the jerk paste until well coated. Cover and refrigerate for 1 hour..</li><br/>",
                     "<li class='animated fadeInLeft'>Meanwhile, make the jerk sauce: Combine 2-4 tablespoons of the jerk paste with the pineapple juice and ketchup. Season to taste with salt.</li><br/>",
                     "<li class='animated fadeInLeft'>Thread the skewers with 2 pieces each of the marinated chicken, red onion, bell pepper, and pineapple, alternating ingredients.</li><br/>",
                     "<li class='animated fadeInLeft'>Top completed enchiladas with the remaining enchilada sauce and cheese.</li><br/>",
                     "<li class='animated fadeInLeft'>Arrange the skewers on the prepared baking sheets. Season with salt. Brush about ⅓ cup (85 G) of the jerk sauce over the skewers. Reserve the remaining sauce.</li><br/>",
                     "<li class='animated fadeInLeft'>Roast the skewers for 22-25 minutes, turning halfway, until the chicken is cooked to an internal temperature of 165ºF (75ºC).</li><br/>",
                     "<li class='animated fadeInLeft'>Remove the baking sheets from the oven and discard the parchment paper, then return the skewers to the pans. Turn the broiler to high.</li><br/>",
                     "<li class='animated fadeInLeft'>Baste the skewers on all sides with the jerk sauce.</li><br/>",
                     "<li class='animated fadeInLeft'>Broil for 3-4 minutes, until the vegetables just begin to char and the sauce is slightly caramelized.</li><br/>",
                     "<li class='animated fadeInLeft'>Transfer the skewers to a platter. Squeeze the lime wedges over the hot skewers and garnish with the cilantro.</li><br/>",
                     "<li class='animated fadeInLeft'>Enjoy!</li><br/>",
                     ]
},
{id:4,
    name:"Bacon BBQ Chicken Loaf",
    img:"pic/chicken/4chicken.jpeg",
    cooker:"Matthew Johnson",
    Ingredients:[ "<h6 class='animated fadeInDown'>for 6 servingss</h6><br/>",
                  "<h6 class='animated fadeInLeft'>5 chicken breasts</h6><br/>",
                  "<h6 class='animated fadeInLeft'>1 tablespoon salt</h6><br/>",
                  "<h6 class='animated fadeInLeft'>1 tablespoon garlic powder</h6><br/>",
                  "<h6 class='animated fadeInLeft'>1 tablespoon smoked paprika</h6><br/>",
                  "<h6 class='animated fadeInLeft'>1 tablespoon onion powder</h6><br/>",
                  "<h6 class='animated fadeInLeft'>1 teaspoon chili powder</h6><br/>",
                  "<h6 class='animated fadeInLeft'>1 teaspoon pepper</h6><br/>",
                  "<h6 class='animated fadeInLeft'>½ teaspoon cayenne pepper</h6><br/>",
                  "<h6 class='animated fadeInLeft'>20 slices bacon</h6><br/>",
                  "<h6 class='animated fadeInLeft'>1 cup BBQ sauce (290 g), divided</h6><br/>",
                  "<h6 class='animated fadeInLeft'>10 slices cheddar cheese</h6><br/>",
                  "<h6 class='animated fadeInLeft'>2 green bell peppers, sliced</h6><br/>",
                  "<h6 class='animated fadeInLeft'>½ red onion, sliced</h6><br/>",
                  "<h6 class='animated fadeInLeft'>2 red bell peppers, sliced</h6><br/>",
                   ],
    Preparation:[
                  "<li class='animated fadeInLeft'>Preheat the oven to 350°F (180°C).</li><br/>",
                  "<li class='animated fadeInLeft'>Cut each chicken breast in half crosswise, then cut the larger half again horizontally, creating 3 cutlets. Transfer to a large bowl.</li><br/>",
                  "<li class='animated fadeInLeft'>In a small bowl, combine the salt, garlic powder, smoked paprika, onion powder, chili powder, black pepper, and cayenne pepper. Stir to combine.</li><br/>",
                  "<li class='animated fadeInLeft'>Pour the spice mix over the chicken cutlets and toss to coat completely in the seasoning. Set the chicken aside.</li><br/>",
                  "<li class='animated fadeInLeft'>Arrange the bacon slices in a 9x5-inch (23x13-cm) loaf pan, making sure the bottom and sides are fully covered, and that the strips hang over the sides.</li><br/>",
                  "<li class='animated fadeInLeft'>Layer in 4 seasoned chicken cutlets, 2 tablespoons of barbecue sauce, 5 slices of cheddar cheese, 4 more chicken cutlets, another 2 tablespoons of barbecue sauce, the green pepper, onion, 2 tablespoons of barbecue sauce, the red pepper, 5 remaining cheese slices, and the remaining chicken. Then, wrap the overhanging strips of bacon over the top of the loaf.</li><br/>",
                  "<li class='animated fadeInLeft'>Arrange the skewers on the prepared baking sheets. Season with salt. Brush about ⅓ cup (85 G) of the jerk sauce over the skewers. Reserve the remaining sauce.</li><br/>",
                  "<li class='animated fadeInLeft'>Cover the loaf with foil and bake for 1 hour. Then remove the foil, drain any excess fat, and bake for another 30 minutes uncovered, making sure the chicken is cooked through and the bacon is brown and crispy.</li><br/>",
                  "<li class='animated fadeInLeft'>Remove the bacon loaf from the oven and turn on the broiler. Invert the loaf onto a wire rack set atop a baking sheet and baste the loaf with the remaining barbecue sauce.</li><br/>",
                  "<li class='animated fadeInLeft'>Broil for 5 minutes, until the glaze dries slightly.</li><br/>",
                  "<li class='animated fadeInLeft'>Slice and serve with rolls or other barbecue party food.</li><br/>",
                  "<li class='animated fadeInLeft'>Enjoy!</li><br/>",
                  ]
},
{id:5,
    name:"Chicken Parmesan Bread Bowl",
    img:"pic/chicken/5chicken.jpeg",
    cooker:"Betsy Carter",
    Ingredients:[  "<h6 class='animated fadeInDown'>for 6 servings</h6><br/>",
                   "<h6 class='animated fadeInLeft'>1 cup breadcrumb (115 g)</h6><br/>",
                   "<h6 class='animated fadeInLeft'>½ teaspoon fresh parsley, chopped</h6><br/>",
                   "<h6 class='animated fadeInLeft'>½ teaspoon garlic powder</h6><br/>",
                   "<h6 class='animated fadeInLeft'>½ teaspoon onion powder</h6><br/>",
                   "<h6 class='animated fadeInLeft'>¼ teaspoon dried oregano</h6><br/>",
                   "<h6 class='animated fadeInLeft'>½ teaspoon salt</h6><br/>",
                   "<h6 class='animated fadeInLeft'>¼ teaspoon pepper</h6><br/>",
                   "<h6 class='animated fadeInLeft'>1 cup flour (125 g)</h6><br/>",
                   "<h6 class='animated fadeInLeft'>3 eggs, beaten</h6><br/>",
                   "<h6 class='animated fadeInLeft'>2 boneless, skinless chicken breasts, thinly sliced</h6><br/>",
                   "<h6 class='animated fadeInLeft'>oil, for frying.</h6><br/>",
                   "<h6 class='animated fadeInLeft'>1 bread bowl</h6><br/>",
                   "<h6 class='animated fadeInLeft'>1 cup marinara sauce (260 g)</h6><br/>",
                   "<h6 class='animated fadeInLeft'>8 oz mozzarella cheese (225 g)</h6><br/>",
                   "<h6 class='animated fadeInLeft'>½ cup shredded parmesan cheese (50 g)</h6><br/>",
                   "<h6 class='animated fadeInLeft'>3 tablespoons butter, melted</h6><br/>",
                   "<h6 class='animated fadeInLeft'>3 cloves garlic, minced</h6><br/>",
                   "<h6 class='animated fadeInLeft'>1 tablespoon fresh parsley, chopped</h6><br/>",
                   "<h6 class='animated fadeInLeft'>1 tablespoon parmesan cheese, grated</h6><br/>",
                   "<h6 class='animated fadeInLeft'>fresh basil, for serving</h6><br/>",
                   ],
    Preparation:[
                 "<li class='animated fadeInLeft'>In a medium bowl, combine bread crumbs, parsley garlic powder, onion powder, oregano, salt, and pepper to bread crumbs.</li><br/>",
                  "<li class='animated fadeInLeft'>Place flour and eggs in two other medium bowls.</li><br/>",
                  "<li class='animated fadeInLeft'>Roll the chicken breast in the flour, dusting off any excess. Dip the chicken into the egg, then place into the breadcrumbs, coating it completely.</li><br/>",
                  "<li class='animated fadeInLeft'>Heat the oil in a skillet over medium-high heat.</li><br/>",
                  "<li class='animated fadeInLeft'>Once the oil begins to shimmer, fry the breaded chicken strips until both sides are golden brown.</li><br/>",
                  "<li class='animated fadeInLeft'>Remove from heat and drain on a paper towel.</li><br/>",
                  "<li class='animated fadeInLeft'>Arrange the skewers on the prepared baking sheets. Season with salt. Brush about ⅓ cup (85 G) of the jerk sauce over the skewers. Reserve the remaining sauce.</li><br/>",
                  "<li class='animated fadeInLeft'>Preheat oven to 350°F (180˚C).</li><br/>",
                  "<li class='animated fadeInLeft'>Slice the cooked chicken breast into ½-inch (1 cm) thick strips.</li><br/>",
                  "<li class='animated fadeInLeft'>Slice the top of the bread bowl off and scoop out the insides. Save the top of the bowl.</li><br/>",
                  "<li class='animated fadeInLeft'>Spoon and spread some of the marinara sauce on the bottom of the bowl, then layer on mozzarella, Parmesan cheese, chicken strips, marinara, remaining mozzarella, Parmesan, chicken strips, marinara, and remaining Parmesan.</li><br/>",
                  "<li class='animated fadeInLeft'>Place the cap of the bread bowl on top.</li><br/>",
                  "<li class='animated fadeInLeft'>Wrap the bread bowl in foil, then weigh it down with a heavy object for 30 minutes.</li><br/>",
                  "<li class='animated fadeInLeft'>In a small bowl, mix together butter, garlic, parsley, and Parmesan cheese.</li><br/>",
                  "<li class='animated fadeInLeft'>Remove the foil from the bread bowl and brush the garlic butter mixture evenly over it.</li><br/>",
                  "<li class='animated fadeInLeft'>Bake for 30 minutes.</li><br/>",
                  "<li class='animated fadeInLeft'>Cool for 10 minutes and slice.</li><br/>",
                  "<li class='animated fadeInLeft'>Garnish with basil, if desired.</li><br/>",
                  "<li class='animated fadeInLeft'>Enjoy!</li><br/>",
                  ]
},
];

const meat = [
  {id:1,
   name:"French Pepper Steak (Steak Au Poivre)",
   img:"pic/meat/onemeat.jpg",
   cooker:"Jordan Kenna",
   Ingredients:[ "<h5 class='animated fadeInDown'>for 2 servings</h5><br/>",
                 "<h6 class='animated fadeInLeft'>14 oz new york strip steak (400 g), or other steak of good quality</h6><br/>",
                 "<h6 class='animated fadeInLeft'>2 teaspoons kosher salt</h6><br/>",
                 "<h6 class='animated fadeInLeft'>2 tablespoons coarsely ground black pepper</h6><br/>",
                 "<h6 class='animated fadeInLeft'>1 tablespoon vegetable oil</h6><br/>",
                 "<h6 class='animated fadeInLeft'>2 tablespoons butter, divided</h6><br/>",
                 "<h6 class='animated fadeInLeft'>1 cup cream (240 mL)</h6><br/>",
                 "<h6 class='animated fadeInLeft'>⅓ cup brandy or cognac (80 mL)</h6><br/>",
                 "<h6 class='animated fadeInLeft'>1 tablespoon dijon mustard</h6><br/>",],
   Preparation:[
                 "<li class='animated fadeInLeft'>Liberally season steak with salt and pepper, being sure to coat the entire surface of the meat. Using your hands, press the seasoning into the meat to create an even coating.</li><br/>",
                 "<li class='animated fadeInLeft'>Heat the vegetable oil and 1 tablespoon of butter in a large skillet over medium-high heat until just smoking. Add the steak to the pan and sear for 4 minutes. Turn and sear the other side for another 4 minutes, for medium-rare. If steak has a fat-cap on its side, be sure to sear it as well for 30 seconds to 1 minute. Once cooked to desired doneness, transfer the steak to a cutting board to rest.</li><br/>",
                 "<li class='animated fadeInLeft'>Reduce the heat to medium and add the brandy to the skillet. Allow the brandy to cook down for about 1 minute while using a whisk to scrape off any browned bits in the bottom of the pan. Once the brandy has reduced by half, add the cream and continue to whisk until combined. Add the Dijon mustard and remaining tablespoon of butter and continue to cook until mixture begins to reduce and thicken, 5-7 minutes. The final pan sauce should have a rich consistency and coat the back of a spoon. Reduce the heat to low.</li><br/>",
                 "<li class='animated fadeInLeft'>Slice the steak into ½-inch (1.5cm) pieces. Pour cream sauce over the top and serve.</li><br/>",
                 "<li class='animated fadeInLeft'>enjoy!</li><br/>",
                ]
},
 {id:2,
     name:"Skirt Steak With Mustard Sauce As Made By Katano Kasaine",
     img:"pic/meat/twomeat.jpg",
     cooker:"Katie Aubin",
     Ingredients:[ "<h6 class='animated fadeInDown'>for 2 servings</h6><br/>",
                   "<h6 class='animated fadeInLeft'>1 lb skirt steak (455 g), room temperature </h6><br/>",
                   "<h6 class='animated fadeInLeft'>1 teaspoon kosher salt)</h6><br/>",
                   "<h6 class='animated fadeInLeft'>1 teaspoon black pepper</h6><br/>",
                   "<h6 class='animated fadeInLeft'>1 ½ tablespoons olive oil</h6><br/>",
                    "<h6 class='animated fadeInLeft'>¼ cup beef broth (60 mL)</h6><br/>",
                    "<h6 class='animated fadeInLeft'>2 tablespoons dijon mustard</h6><br/>",
                    "<h6 class='animated fadeInLeft'>1 tablespoon unsalted butter</h6><br/>",
                    "<h6 class='animated fadeInLeft'>1 ½ tablespoons capers in brine</h6><br/>",
                    "<h6 class='animated fadeInLeft'>rice, cooked, for serving</h6><br/>",
                    "<h6 class='animated fadeInLeft'>broccoli, steamed, for serving</h6><br/>",
                    ],
     Preparation:[
                   "<li class='animated fadeInLeft'>Cut steak in half crosswise. Season with the salt and pepper.</li><br/>",
                   "<li class='animated fadeInLeft'>Heat the olive oil in a nonstick or stainless steel pan over medium heat for 1 minute. Add 1 portion of steak and cook until a golden brown crust has formed, 4-5 minutes per side. Transfer the seared steak to a plate and repeat with the remaining portion of steak. If the pan is getting too dry, add a bit more olive oil. Let the steaks rest for 3 minutes.</li><br/>",
                   "<li class='animated fadeInLeft'>After the steak has rested, transfer to a cutting board and pour any accumulated meat juices from the plate back into the pan and return to medium heat.</li><br/>",
                   "<li class='animated fadeInLeft'>Add the beef broth and scrape up any brown bits from the bottom of the pan. Add the mustard and butter and stir until combined. Stir in the capers and cook until the sauce thickens slightly, 1-2 minutes.</li><br/>",
                   "<li class='animated fadeInLeft'>Slice the steak into ¼-inch (6 mm) pieces and transfer to serving plates. Pour the sauce over the steak and serve with rice and broccoli.</li><br/>",
                   "<li class='animated fadeInLeft'>Enjoy!</li><br/>",
                   ]
},
 {id:3,
     name:"Paleo Beef and Veggie Stir-fry",
     img:"pic/meat/threemeat.jpg",
     cooker:"Alix Traeger & Ali Clarke",
     Ingredients:[  "<h6 class='animated fadeInDown'> for 6 servings    </h6><br/>",
                    "<h6 class='animated fadeInLeft'> 1 lb flank steak (455 g), trimmed and sliced thin against grain into 2-inch (5 cm) pieces  </h6><br/>",
                    "<h6 class='animated fadeInLeft'> 2 teaspoons lime juice    </h6><br/>",
                    "<h6 class='animated fadeInLeft'> 2 teaspoons coconut amino    </h6><br/>",
                    "<h6 class='animated fadeInLeft'> 2 tablespoons avocado oil, or other oil, divided   </h6><br/>",
                    "<h6 class='animated fadeInLeft'> 3 carrots, peeled and sliced ¼ -inch (6 mm) thick on the bias  </h6><br/>",
                    "<h6 class='animated fadeInLeft'> 1 head small napa cabbage, thinly sliced, plus more for serving    </h6><br/>",
                    "<h6 class='animated fadeInLeft'> 3 fresh scallions, minced, plus more for thinly sliced for garnish    </h6><br/>",
                    "<h6 class='animated fadeInLeft'> 1 tablespoon ginger, grated   </h6><br/>",
                    "<h6 class='animated fadeInLeft'> 4 cloves garlic, minced    </h6><br/>",
                    "<h5 class='animated fadeInDown'> Sauce    </h5><br/>",
                    "<h6 class='animated fadeInLeft'> 6 tablespoons coconut amino    </h6><br/>",
                    "<h6 class='animated fadeInLeft'> 2 tablespoons lime juice    </h6><br/>",
                    "<h6 class='animated fadeInLeft'> 1 ½ teaspoons tapioca flour    </h6><br/>",
                    ],
     Preparation:[
                  "<li class='animated fadeInLeft'>  Add the flank steak, coconut aminos, and lime juice to a bowl, and toss to combine. Set aside to marinate for 10 minutes.   </li><br/>",
                   "<li class='animated fadeInLeft'>  Heat 1 tablespoon of oil over medium-high heat in a large nonstick skillet. Place half the meat in the skillet and sear for 1 minute on each side.   </li><br/>",
                   "<li class='animated fadeInLeft'>  Place the seared steak in a clean bowl and repeat with the second batch, draining excess liquid from the skillet as needed.   </li><br/>",
                   "<li class='animated fadeInLeft'>  Once all of the meat has been seared and removed from the pan, heat the remaining 1 tablespoon of oil in the pan. Add in the carrots and sauté until softened, about 5 minutes.   </li><br/>",
                   "<li class='animated fadeInLeft'>  Add the Napa cabbage to the pan and quickly toss with the carrots.   </li><br/>",
                   "<li class='animated fadeInLeft'>  Move the cabbage and carrots away from the center of the pan and sprinkle in the scallions, ginger, and garlic. Stir the mixture in the center of the pan until fragrant, about 30 seconds.   </li><br/>",
                   "<li class='animated fadeInLeft'> Mix all contents of the pan together and toss in the meat.   </li><br/>",
                   "<li class='animated fadeInLeft'>  Pour in the coconut aminos, lime juice, and tapioca flour. Stir the contents of the pan until well combined and the sauce has thickened, about 1-2 minutes. Remove from heat.   </li><br/>",
                   "<li class='animated fadeInLeft'>  Divided the mixture between bowls filled with Napa cabbage and garnish with scallions.  </li><br/>",
                   "<li class='animated fadeInLeft'>  Enjoy!   </li><br/>",
                   ]
},
{id:4,
  name:"Cheesesteak Roll-Ups",
  img:"pic/meat/fourmeat.jpg",
  cooker:"Frank Tiu & Jacqueline Tris",
  Ingredients:[ "<h6 class='animated fadeInDown'> for 4 servings    </h6><br/>",
                "<h6 class='animated fadeInLeft'> 1 tablespoon vegetable oil    </h6><br/>",
                "<h6 class='animated fadeInLeft'> 1 white onion, sliced    </h6><br/>",
                "<h6 class='animated fadeInLeft'>1 red bell pepper, seeded and sliced    </h6><br/>",
                "<h6 class='animated fadeInLeft'> green bell pepper, seeded and sliced    </h6><br/>",
                "<h6 class='animated fadeInLeft'> 1 tablespoon kosher salt, plus 2 teaspoons, divided    </h6><br/>",
                "<h6 class='animated fadeInLeft'> 1 teaspoon garlic powder    </h6><br/>",
                "<h6 class='animated fadeInLeft'> 1 tablespoon pepper, plus 1 teaspoon, divided    </h6><br/>",
                "<h6 class='animated fadeInLeft'> 2 lb flank steak (910 g)    </h6><br/>",
                "<h6 class='animated fadeInLeft'> 14 slices provolone cheese, divided   </h6><br/>",
                 ],
  Preparation:[
                "<li class='animated fadeInLeft'>  Preheat the oven to 425°F (220°C).  </li><br/>",
                "<li class='animated fadeInLeft'>  Heat the vegetable oil in a large pan over high heat. Add the onion and cook for 10 minutes, until translucent and the edges start to brown.  </li><br/>",
                "<li class='animated fadeInLeft'>  Push the onion to one side of the pan and add the red and green bell peppers to the pan. Season with 2 teaspoons of salt, 1 teaspoon of garlic powder, and 1 teaspoon of pepper, and cook until the peppers soften, about 5 minutes. Remove from the pan and set aside.  </li><br/>",
                "<li class='animated fadeInLeft'>  Place the steak on the cutting board, and cover with a piece of plastic wrap. Pound with a meat mallet or rolling pin to about ½-inch (1 ¼ cm) thick.  </li><br/>",
                "<li class='animated fadeInLeft'>  Remove the plastic wrap and season the steak on both sides with 1 tablespoon of salt and 1 tablespoon of pepper.  </li><br/>",
                "<li class='animated fadeInLeft'>  Line 7 slices of Provolone cheese along the bottom edge of the steak. Place the sautéed vegetables on top.  </li><br/>",
                "<li class='animated fadeInLeft'>  Starting from the bottom, roll up the steak, encasing the cheese and vegetables inside.  </li><br/>",
                "<li class='animated fadeInLeft'>  Top with the remaining 7 slices of Provolone and secure with skewers or toothpicks.  </li><br/>",
                "<li class='animated fadeInLeft'>  Transfer the steak roll to a baking sheet and bake for 30 minutes, until cheese is melty and the steak is cooked through to your preference.  </li><br/>",
                "<li class='animated fadeInLeft'>  Rest for 10 minutes before slicing between the skewers and serving.  </li><br/>",
                "<li class='animated fadeInLeft'>  Enjoy!  </li><br/>",
                ]
},
{id:5,
  name:"Corned Beef And Cabbage",
  img:"pic/meat/fivemeat.jpg",
  cooker:"Matthew Johnson",
  Ingredients:[  "<h6 class='animated fadeInDown'>  for 6 servings    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  2 qt water (1.8 L)    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  2 cups kosher salt (480 g)   </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  1 cup brown sugar (220 g)    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  2 teaspoons pink curing salt    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  5 cloves garlic, crushed    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  1 fresh ginger, 2 in (5 cm) sliced   </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  1 cinnamon stick, broken into pieces    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  3 bay leaves, crumbled    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  1 tablespoon mustard seed   </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  1 tablespoon black peppercorn    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  8 whole allspice berries   </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  12 juniper berries    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  8 whole cloves    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  2 lb ice (910 g)    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  5 lb beef brisket (2.2 kg), good-quality, trimmed   </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  1 large yellow onion, chopped   </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  3 celery stalks, chopped    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  2 large carrots, chopped    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  ginger beer, 2 bottles    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  dark extra-stout beer, 2 bottles   </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  1 ½ lb small red potato (680 g)   </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  9 carrots, halved crosswise   </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  1 medium green cabbage, quartered   </h6><br/>",
                 "<h6 class='animated fadeInLeft'>  5 lb corned beef brisket (2.2 kg), thinly sliced   </h6><br/>",
                 ],
  Preparation:[
               "<li class='animated fadeInLeft'>  In a very large pot, combine the water, kosher salt, brown sugar, pink curing salt, garlic, ginger, cinnamon stick, bay leaves, mustard seeds, peppercorns, allspice berries, juniper berries, and cloves. Stir and bring to a boil over high heat.  </li><br/>",
                "<li class='animated fadeInLeft'>  Once the brine is boiling, remove from the heat and add the ice to bring the temperature below 45˚F (7˚C).  </li><br/>",
                "<li class='animated fadeInLeft'>  Place the brisket in a large plastic storage container with a lid. Pour the cooled brine over the meat. Cover and brine the beef in the refrigerator for 5–7 days, flipping once a day.  </li><br/>",
                "<li class='animated fadeInLeft'>  Once the brisket is brined, remove the beef from the liquid and transfer to a pot large enough for it to sit flat on the bottom. Add the onion, celery, carrot, ginger beer, and beer. Bring to a boil over high heat, then reduce the heat to low, cover, and gently simmer for 2½–3 hours, or until the meat is fork-tender. Remove the meat from the pot and let cool. If making corned beef and cabbage, reserve the cooking liquid. Otherwise, discard. </li><br/>",
                "<li class='animated fadeInLeft'>  Thinly slice the brisket against the grain for sandwiches or corned beef and cabbage, or dice for corned beef hash.  </li><br/>",
                "<li class='animated fadeInLeft'>  Return the corned beef cooking liquid to a boil over medium-high heat. (If starting with new cooking liquid, combine the chicken broth, water, chopped carrots, celery, and onion in a large pot and bring to a boil.)  </li><br/>",
                "<li class='animated fadeInLeft'>  Once the cooking liquid is boiling, add the potatoes and cook for 10 minutes, until half-cooked. Add the halved carrots and cabbage, cover, and cook for 10–15 minutes more, until the vegetables are tender.  </li><br/>",
                "<li class='animated fadeInLeft'>  Transfer the vegetables to a serving platter with the sliced brisket and ladle the cooking liquid over.  </li><br/>",
                "<li class='animated fadeInLeft'>  Enjoy!  </li><br/>",
                ]
},
];


const vegetarian = [
  {id:1,
    name:"French Pepper Steak (Steak Au Poivre)",
    img:"pic/vegetarian/onevega.jpg",
    cooker:"Jordan Kenna",
    Ingredients:[ "<h5 class='animated fadeInDown'>for 2 servings</h5><br/>",
                  "<h6 class='animated fadeInLeft'>14 oz new york strip steak (400 g), or other steak of good quality</h6><br/>",
                  "<h6 class='animated fadeInLeft'>2 teaspoons kosher salt</h6><br/>",
                  "<h6 class='animated fadeInLeft'>2 tablespoons coarsely ground black pepper</h6><br/>",
                  "<h6 class='animated fadeInLeft'>1 tablespoon vegetable oil</h6><br/>",
                  "<h6 class='animated fadeInLeft'>2 tablespoons butter, divided</h6><br/>",
                  "<h6 class='animated fadeInLeft'>1 cup cream (240 mL)</h6><br/>",
                  "<h6 class='animated fadeInLeft'>⅓ cup brandy or cognac (80 mL)</h6><br/>",
                  "<h6 class='animated fadeInLeft'>1 tablespoon dijon mustard</h6><br/>",],
    Preparation:[
                  "<li class='animated fadeInLeft'>Liberally season steak with salt and pepper, being sure to coat the entire surface of the meat. Using your hands, press the seasoning into the meat to create an even coating.</li><br/>",
                  "<li class='animated fadeInLeft'>Heat the vegetable oil and 1 tablespoon of butter in a large skillet over medium-high heat until just smoking. Add the steak to the pan and sear for 4 minutes. Turn and sear the other side for another 4 minutes, for medium-rare. If steak has a fat-cap on its side, be sure to sear it as well for 30 seconds to 1 minute. Once cooked to desired doneness, transfer the steak to a cutting board to rest.</li><br/>",
                  "<li class='animated fadeInLeft'>Reduce the heat to medium and add the brandy to the skillet. Allow the brandy to cook down for about 1 minute while using a whisk to scrape off any browned bits in the bottom of the pan. Once the brandy has reduced by half, add the cream and continue to whisk until combined. Add the Dijon mustard and remaining tablespoon of butter and continue to cook until mixture begins to reduce and thicken, 5-7 minutes. The final pan sauce should have a rich consistency and coat the back of a spoon. Reduce the heat to low.</li><br/>",
                  "<li class='animated fadeInLeft'>Slice the steak into ½-inch (1.5cm) pieces. Pour cream sauce over the top and serve.</li><br/>",
                  "<li class='animated fadeInLeft'>enjoy!</li><br/>",
                 ]
 },
  {id:2,
      name:"Skirt Steak With Mustard Sauce As Made By Katano Kasaine",
      img:"pic/vegetarian/twovega.jpg",
      cooker:"Katie Aubin",
      Ingredients:[ "<h6 class='animated fadeInDown'>for 2 servings</h6><br/>",
                    "<h6 class='animated fadeInLeft'>1 lb skirt steak (455 g), room temperature </h6><br/>",
                    "<h6 class='animated fadeInLeft'>1 teaspoon kosher salt)</h6><br/>",
                    "<h6 class='animated fadeInLeft'>1 teaspoon black pepper</h6><br/>",
                    "<h6 class='animated fadeInLeft'>1 ½ tablespoons olive oil</h6><br/>",
                     "<h6 class='animated fadeInLeft'>¼ cup beef broth (60 mL)</h6><br/>",
                     "<h6 class='animated fadeInLeft'>2 tablespoons dijon mustard</h6><br/>",
                     "<h6 class='animated fadeInLeft'>1 tablespoon unsalted butter</h6><br/>",
                     "<h6 class='animated fadeInLeft'>1 ½ tablespoons capers in brine</h6><br/>",
                     "<h6 class='animated fadeInLeft'>rice, cooked, for serving</h6><br/>",
                     "<h6 class='animated fadeInLeft'>broccoli, steamed, for serving</h6><br/>",
                     ],
      Preparation:[
                    "<li class='animated fadeInLeft'>Cut steak in half crosswise. Season with the salt and pepper.</li><br/>",
                    "<li class='animated fadeInLeft'>Heat the olive oil in a nonstick or stainless steel pan over medium heat for 1 minute. Add 1 portion of steak and cook until a golden brown crust has formed, 4-5 minutes per side. Transfer the seared steak to a plate and repeat with the remaining portion of steak. If the pan is getting too dry, add a bit more olive oil. Let the steaks rest for 3 minutes.</li><br/>",
                    "<li class='animated fadeInLeft'>After the steak has rested, transfer to a cutting board and pour any accumulated meat juices from the plate back into the pan and return to medium heat.</li><br/>",
                    "<li class='animated fadeInLeft'>Add the beef broth and scrape up any brown bits from the bottom of the pan. Add the mustard and butter and stir until combined. Stir in the capers and cook until the sauce thickens slightly, 1-2 minutes.</li><br/>",
                    "<li class='animated fadeInLeft'>Slice the steak into ¼-inch (6 mm) pieces and transfer to serving plates. Pour the sauce over the steak and serve with rice and broccoli.</li><br/>",
                    "<li class='animated fadeInLeft'>Enjoy!</li><br/>",
                    ]
 },
  {id:3,
      name:"Paleo Beef and Veggie Stir-fry",
      img:"pic/vegetarian/threevega.jpg",
      cooker:"Alix Traeger & Ali Clarke",
      Ingredients:[  "<h6 class='animated fadeInDown'> for 6 servings    </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 1 lb flank steak (455 g), trimmed and sliced thin against grain into 2-inch (5 cm) pieces  </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 2 teaspoons lime juice    </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 2 teaspoons coconut amino    </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 2 tablespoons avocado oil, or other oil, divided   </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 3 carrots, peeled and sliced ¼ -inch (6 mm) thick on the bias  </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 1 head small napa cabbage, thinly sliced, plus more for serving    </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 3 fresh scallions, minced, plus more for thinly sliced for garnish    </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 1 tablespoon ginger, grated   </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 4 cloves garlic, minced    </h6><br/>",
                     "<h5 class='animated fadeInDown'> Sauce    </h5><br/>",
                     "<h6 class='animated fadeInLeft'> 6 tablespoons coconut amino    </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 2 tablespoons lime juice    </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 1 ½ teaspoons tapioca flour    </h6><br/>",
                     ],
      Preparation:[
                   "<li class='animated fadeInLeft'>  Add the flank steak, coconut aminos, and lime juice to a bowl, and toss to combine. Set aside to marinate for 10 minutes.   </li><br/>",
                    "<li class='animated fadeInLeft'>  Heat 1 tablespoon of oil over medium-high heat in a large nonstick skillet. Place half the meat in the skillet and sear for 1 minute on each side.   </li><br/>",
                    "<li class='animated fadeInLeft'>  Place the seared steak in a clean bowl and repeat with the second batch, draining excess liquid from the skillet as needed.   </li><br/>",
                    "<li class='animated fadeInLeft'>  Once all of the meat has been seared and removed from the pan, heat the remaining 1 tablespoon of oil in the pan. Add in the carrots and sauté until softened, about 5 minutes.   </li><br/>",
                    "<li class='animated fadeInLeft'>  Add the Napa cabbage to the pan and quickly toss with the carrots.   </li><br/>",
                    "<li class='animated fadeInLeft'>  Move the cabbage and carrots away from the center of the pan and sprinkle in the scallions, ginger, and garlic. Stir the mixture in the center of the pan until fragrant, about 30 seconds.   </li><br/>",
                    "<li class='animated fadeInLeft'> Mix all contents of the pan together and toss in the meat.   </li><br/>",
                    "<li class='animated fadeInLeft'>  Pour in the coconut aminos, lime juice, and tapioca flour. Stir the contents of the pan until well combined and the sauce has thickened, about 1-2 minutes. Remove from heat.   </li><br/>",
                    "<li class='animated fadeInLeft'>  Divided the mixture between bowls filled with Napa cabbage and garnish with scallions.  </li><br/>",
                    "<li class='animated fadeInLeft'>  Enjoy!   </li><br/>",
                    ]
 },
 {id:4,
   name:"Cheesesteak Roll-Ups",
   img:"pic/vegetarian/fourvega.jpeg",
   cooker:"Frank Tiu & Jacqueline Tris",
   Ingredients:[ "<h6 class='animated fadeInDown'> for 4 servings    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> 1 tablespoon vegetable oil    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> 1 white onion, sliced    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>1 red bell pepper, seeded and sliced    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> green bell pepper, seeded and sliced    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> 1 tablespoon kosher salt, plus 2 teaspoons, divided    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> 1 teaspoon garlic powder    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> 1 tablespoon pepper, plus 1 teaspoon, divided    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> 2 lb flank steak (910 g)    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> 14 slices provolone cheese, divided   </h6><br/>",
                  ],
   Preparation:[
                 "<li class='animated fadeInLeft'>  Preheat the oven to 425°F (220°C).  </li><br/>",
                 "<li class='animated fadeInLeft'>  Heat the vegetable oil in a large pan over high heat. Add the onion and cook for 10 minutes, until translucent and the edges start to brown.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Push the onion to one side of the pan and add the red and green bell peppers to the pan. Season with 2 teaspoons of salt, 1 teaspoon of garlic powder, and 1 teaspoon of pepper, and cook until the peppers soften, about 5 minutes. Remove from the pan and set aside.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Place the steak on the cutting board, and cover with a piece of plastic wrap. Pound with a meat mallet or rolling pin to about ½-inch (1 ¼ cm) thick.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Remove the plastic wrap and season the steak on both sides with 1 tablespoon of salt and 1 tablespoon of pepper.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Line 7 slices of Provolone cheese along the bottom edge of the steak. Place the sautéed vegetables on top.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Starting from the bottom, roll up the steak, encasing the cheese and vegetables inside.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Top with the remaining 7 slices of Provolone and secure with skewers or toothpicks.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Transfer the steak roll to a baking sheet and bake for 30 minutes, until cheese is melty and the steak is cooked through to your preference.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Rest for 10 minutes before slicing between the skewers and serving.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Enjoy!  </li><br/>",
                 ]
 },
 {id:5,
   name:"Corned Beef And Cabbage",
   img:"pic/vegetarian/fivevega.jpg",
   cooker:"Matthew Johnson",
   Ingredients:[  "<h6 class='animated fadeInDown'>  for 6 servings    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  2 qt water (1.8 L)    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  2 cups kosher salt (480 g)   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 cup brown sugar (220 g)    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  2 teaspoons pink curing salt    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  5 cloves garlic, crushed    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 fresh ginger, 2 in (5 cm) sliced   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 cinnamon stick, broken into pieces    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  3 bay leaves, crumbled    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 tablespoon mustard seed   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 tablespoon black peppercorn    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  8 whole allspice berries   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  12 juniper berries    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  8 whole cloves    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  2 lb ice (910 g)    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  5 lb beef brisket (2.2 kg), good-quality, trimmed   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 large yellow onion, chopped   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  3 celery stalks, chopped    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  2 large carrots, chopped    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  ginger beer, 2 bottles    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  dark extra-stout beer, 2 bottles   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 ½ lb small red potato (680 g)   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  9 carrots, halved crosswise   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 medium green cabbage, quartered   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  5 lb corned beef brisket (2.2 kg), thinly sliced   </h6><br/>",
                  ],
   Preparation:[
                "<li class='animated fadeInLeft'>  In a very large pot, combine the water, kosher salt, brown sugar, pink curing salt, garlic, ginger, cinnamon stick, bay leaves, mustard seeds, peppercorns, allspice berries, juniper berries, and cloves. Stir and bring to a boil over high heat.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Once the brine is boiling, remove from the heat and add the ice to bring the temperature below 45˚F (7˚C).  </li><br/>",
                 "<li class='animated fadeInLeft'>  Place the brisket in a large plastic storage container with a lid. Pour the cooled brine over the meat. Cover and brine the beef in the refrigerator for 5–7 days, flipping once a day.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Once the brisket is brined, remove the beef from the liquid and transfer to a pot large enough for it to sit flat on the bottom. Add the onion, celery, carrot, ginger beer, and beer. Bring to a boil over high heat, then reduce the heat to low, cover, and gently simmer for 2½–3 hours, or until the meat is fork-tender. Remove the meat from the pot and let cool. If making corned beef and cabbage, reserve the cooking liquid. Otherwise, discard. </li><br/>",
                 "<li class='animated fadeInLeft'>  Thinly slice the brisket against the grain for sandwiches or corned beef and cabbage, or dice for corned beef hash.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Return the corned beef cooking liquid to a boil over medium-high heat. (If starting with new cooking liquid, combine the chicken broth, water, chopped carrots, celery, and onion in a large pot and bring to a boil.)  </li><br/>",
                 "<li class='animated fadeInLeft'>  Once the cooking liquid is boiling, add the potatoes and cook for 10 minutes, until half-cooked. Add the halved carrots and cabbage, cover, and cook for 10–15 minutes more, until the vegetables are tender.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Transfer the vegetables to a serving platter with the sliced brisket and ladle the cooking liquid over.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Enjoy!  </li><br/>",
                 ]
 },
];

const children = [
  {id:1,
    name:"French Pepper Steak (Steak Au Poivre)",
    img:"pic/children/onechild.jpg",
    cooker:"Jordan Kenna",
    Ingredients:[ "<h5 class='animated fadeInDown'>for 2 servings</h5><br/>",
                  "<h6 class='animated fadeInLeft'>14 oz new york strip steak (400 g), or other steak of good quality</h6><br/>",
                  "<h6 class='animated fadeInLeft'>2 teaspoons kosher salt</h6><br/>",
                  "<h6 class='animated fadeInLeft'>2 tablespoons coarsely ground black pepper</h6><br/>",
                  "<h6 class='animated fadeInLeft'>1 tablespoon vegetable oil</h6><br/>",
                  "<h6 class='animated fadeInLeft'>2 tablespoons butter, divided</h6><br/>",
                  "<h6 class='animated fadeInLeft'>1 cup cream (240 mL)</h6><br/>",
                  "<h6 class='animated fadeInLeft'>⅓ cup brandy or cognac (80 mL)</h6><br/>",
                  "<h6 class='animated fadeInLeft'>1 tablespoon dijon mustard</h6><br/>",],
    Preparation:[
                  "<li class='animated fadeInLeft'>Liberally season steak with salt and pepper, being sure to coat the entire surface of the meat. Using your hands, press the seasoning into the meat to create an even coating.</li><br/>",
                  "<li class='animated fadeInLeft'>Heat the vegetable oil and 1 tablespoon of butter in a large skillet over medium-high heat until just smoking. Add the steak to the pan and sear for 4 minutes. Turn and sear the other side for another 4 minutes, for medium-rare. If steak has a fat-cap on its side, be sure to sear it as well for 30 seconds to 1 minute. Once cooked to desired doneness, transfer the steak to a cutting board to rest.</li><br/>",
                  "<li class='animated fadeInLeft'>Reduce the heat to medium and add the brandy to the skillet. Allow the brandy to cook down for about 1 minute while using a whisk to scrape off any browned bits in the bottom of the pan. Once the brandy has reduced by half, add the cream and continue to whisk until combined. Add the Dijon mustard and remaining tablespoon of butter and continue to cook until mixture begins to reduce and thicken, 5-7 minutes. The final pan sauce should have a rich consistency and coat the back of a spoon. Reduce the heat to low.</li><br/>",
                  "<li class='animated fadeInLeft'>Slice the steak into ½-inch (1.5cm) pieces. Pour cream sauce over the top and serve.</li><br/>",
                  "<li class='animated fadeInLeft'>enjoy!</li><br/>",
                 ]
 },
  {id:2,
      name:"Skirt Steak With Mustard Sauce As Made By Katano Kasaine",
      img:"pic/children/twochild.jpg",
      cooker:"Katie Aubin",
      Ingredients:[ "<h6 class='animated fadeInDown'>for 2 servings</h6><br/>",
                    "<h6 class='animated fadeInLeft'>1 lb skirt steak (455 g), room temperature </h6><br/>",
                    "<h6 class='animated fadeInLeft'>1 teaspoon kosher salt)</h6><br/>",
                    "<h6 class='animated fadeInLeft'>1 teaspoon black pepper</h6><br/>",
                    "<h6 class='animated fadeInLeft'>1 ½ tablespoons olive oil</h6><br/>",
                     "<h6 class='animated fadeInLeft'>¼ cup beef broth (60 mL)</h6><br/>",
                     "<h6 class='animated fadeInLeft'>2 tablespoons dijon mustard</h6><br/>",
                     "<h6 class='animated fadeInLeft'>1 tablespoon unsalted butter</h6><br/>",
                     "<h6 class='animated fadeInLeft'>1 ½ tablespoons capers in brine</h6><br/>",
                     "<h6 class='animated fadeInLeft'>rice, cooked, for serving</h6><br/>",
                     "<h6 class='animated fadeInLeft'>broccoli, steamed, for serving</h6><br/>",
                     ],
      Preparation:[
                    "<li class='animated fadeInLeft'>Cut steak in half crosswise. Season with the salt and pepper.</li><br/>",
                    "<li class='animated fadeInLeft'>Heat the olive oil in a nonstick or stainless steel pan over medium heat for 1 minute. Add 1 portion of steak and cook until a golden brown crust has formed, 4-5 minutes per side. Transfer the seared steak to a plate and repeat with the remaining portion of steak. If the pan is getting too dry, add a bit more olive oil. Let the steaks rest for 3 minutes.</li><br/>",
                    "<li class='animated fadeInLeft'>After the steak has rested, transfer to a cutting board and pour any accumulated meat juices from the plate back into the pan and return to medium heat.</li><br/>",
                    "<li class='animated fadeInLeft'>Add the beef broth and scrape up any brown bits from the bottom of the pan. Add the mustard and butter and stir until combined. Stir in the capers and cook until the sauce thickens slightly, 1-2 minutes.</li><br/>",
                    "<li class='animated fadeInLeft'>Slice the steak into ¼-inch (6 mm) pieces and transfer to serving plates. Pour the sauce over the steak and serve with rice and broccoli.</li><br/>",
                    "<li class='animated fadeInLeft'>Enjoy!</li><br/>",
                    ]
 },
  {id:3,
      name:"Paleo Beef and Veggie Stir-fry",
      img:"pic/children/threechild.jpg",
      cooker:"Alix Traeger & Ali Clarke",
      Ingredients:[  "<h6 class='animated fadeInDown'> for 6 servings    </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 1 lb flank steak (455 g), trimmed and sliced thin against grain into 2-inch (5 cm) pieces  </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 2 teaspoons lime juice    </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 2 teaspoons coconut amino    </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 2 tablespoons avocado oil, or other oil, divided   </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 3 carrots, peeled and sliced ¼ -inch (6 mm) thick on the bias  </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 1 head small napa cabbage, thinly sliced, plus more for serving    </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 3 fresh scallions, minced, plus more for thinly sliced for garnish    </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 1 tablespoon ginger, grated   </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 4 cloves garlic, minced    </h6><br/>",
                     "<h5 class='animated fadeInDown'> Sauce    </h5><br/>",
                     "<h6 class='animated fadeInLeft'> 6 tablespoons coconut amino    </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 2 tablespoons lime juice    </h6><br/>",
                     "<h6 class='animated fadeInLeft'> 1 ½ teaspoons tapioca flour    </h6><br/>",
                     ],
      Preparation:[
                   "<li class='animated fadeInLeft'>  Add the flank steak, coconut aminos, and lime juice to a bowl, and toss to combine. Set aside to marinate for 10 minutes.   </li><br/>",
                    "<li class='animated fadeInLeft'>  Heat 1 tablespoon of oil over medium-high heat in a large nonstick skillet. Place half the meat in the skillet and sear for 1 minute on each side.   </li><br/>",
                    "<li class='animated fadeInLeft'>  Place the seared steak in a clean bowl and repeat with the second batch, draining excess liquid from the skillet as needed.   </li><br/>",
                    "<li class='animated fadeInLeft'>  Once all of the meat has been seared and removed from the pan, heat the remaining 1 tablespoon of oil in the pan. Add in the carrots and sauté until softened, about 5 minutes.   </li><br/>",
                    "<li class='animated fadeInLeft'>  Add the Napa cabbage to the pan and quickly toss with the carrots.   </li><br/>",
                    "<li class='animated fadeInLeft'>  Move the cabbage and carrots away from the center of the pan and sprinkle in the scallions, ginger, and garlic. Stir the mixture in the center of the pan until fragrant, about 30 seconds.   </li><br/>",
                    "<li class='animated fadeInLeft'> Mix all contents of the pan together and toss in the meat.   </li><br/>",
                    "<li class='animated fadeInLeft'>  Pour in the coconut aminos, lime juice, and tapioca flour. Stir the contents of the pan until well combined and the sauce has thickened, about 1-2 minutes. Remove from heat.   </li><br/>",
                    "<li class='animated fadeInLeft'>  Divided the mixture between bowls filled with Napa cabbage and garnish with scallions.  </li><br/>",
                    "<li class='animated fadeInLeft'>  Enjoy!   </li><br/>",
                    ]
 },
 {id:4,
   name:"Cheesesteak Roll-Ups",
   img:"pic/children/fourchild.jpg",
   cooker:"Frank Tiu & Jacqueline Tris",
   Ingredients:[ "<h6 class='animated fadeInDown'> for 4 servings    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> 1 tablespoon vegetable oil    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> 1 white onion, sliced    </h6><br/>",
                 "<h6 class='animated fadeInLeft'>1 red bell pepper, seeded and sliced    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> green bell pepper, seeded and sliced    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> 1 tablespoon kosher salt, plus 2 teaspoons, divided    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> 1 teaspoon garlic powder    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> 1 tablespoon pepper, plus 1 teaspoon, divided    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> 2 lb flank steak (910 g)    </h6><br/>",
                 "<h6 class='animated fadeInLeft'> 14 slices provolone cheese, divided   </h6><br/>",
                  ],
   Preparation:[
                 "<li class='animated fadeInLeft'>  Preheat the oven to 425°F (220°C).  </li><br/>",
                 "<li class='animated fadeInLeft'>  Heat the vegetable oil in a large pan over high heat. Add the onion and cook for 10 minutes, until translucent and the edges start to brown.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Push the onion to one side of the pan and add the red and green bell peppers to the pan. Season with 2 teaspoons of salt, 1 teaspoon of garlic powder, and 1 teaspoon of pepper, and cook until the peppers soften, about 5 minutes. Remove from the pan and set aside.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Place the steak on the cutting board, and cover with a piece of plastic wrap. Pound with a meat mallet or rolling pin to about ½-inch (1 ¼ cm) thick.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Remove the plastic wrap and season the steak on both sides with 1 tablespoon of salt and 1 tablespoon of pepper.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Line 7 slices of Provolone cheese along the bottom edge of the steak. Place the sautéed vegetables on top.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Starting from the bottom, roll up the steak, encasing the cheese and vegetables inside.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Top with the remaining 7 slices of Provolone and secure with skewers or toothpicks.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Transfer the steak roll to a baking sheet and bake for 30 minutes, until cheese is melty and the steak is cooked through to your preference.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Rest for 10 minutes before slicing between the skewers and serving.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Enjoy!  </li><br/>",
                 ]
 },
 {id:5,
   name:"Corned Beef And Cabbage",
   img:"pic/children/fivechild.jpg",
   cooker:"Matthew Johnson",
   Ingredients:[  "<h6 class='animated fadeInDown'>  for 6 servings    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  2 qt water (1.8 L)    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  2 cups kosher salt (480 g)   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 cup brown sugar (220 g)    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  2 teaspoons pink curing salt    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  5 cloves garlic, crushed    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 fresh ginger, 2 in (5 cm) sliced   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 cinnamon stick, broken into pieces    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  3 bay leaves, crumbled    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 tablespoon mustard seed   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 tablespoon black peppercorn    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  8 whole allspice berries   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  12 juniper berries    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  8 whole cloves    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  2 lb ice (910 g)    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  5 lb beef brisket (2.2 kg), good-quality, trimmed   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 large yellow onion, chopped   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  3 celery stalks, chopped    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  2 large carrots, chopped    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  ginger beer, 2 bottles    </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  dark extra-stout beer, 2 bottles   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 ½ lb small red potato (680 g)   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  9 carrots, halved crosswise   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  1 medium green cabbage, quartered   </h6><br/>",
                  "<h6 class='animated fadeInLeft'>  5 lb corned beef brisket (2.2 kg), thinly sliced   </h6><br/>",
                  ],
   Preparation:[
                "<li class='animated fadeInLeft'>  In a very large pot, combine the water, kosher salt, brown sugar, pink curing salt, garlic, ginger, cinnamon stick, bay leaves, mustard seeds, peppercorns, allspice berries, juniper berries, and cloves. Stir and bring to a boil over high heat.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Once the brine is boiling, remove from the heat and add the ice to bring the temperature below 45˚F (7˚C).  </li><br/>",
                 "<li class='animated fadeInLeft'>  Place the brisket in a large plastic storage container with a lid. Pour the cooled brine over the meat. Cover and brine the beef in the refrigerator for 5–7 days, flipping once a day.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Once the brisket is brined, remove the beef from the liquid and transfer to a pot large enough for it to sit flat on the bottom. Add the onion, celery, carrot, ginger beer, and beer. Bring to a boil over high heat, then reduce the heat to low, cover, and gently simmer for 2½–3 hours, or until the meat is fork-tender. Remove the meat from the pot and let cool. If making corned beef and cabbage, reserve the cooking liquid. Otherwise, discard. </li><br/>",
                 "<li class='animated fadeInLeft'>  Thinly slice the brisket against the grain for sandwiches or corned beef and cabbage, or dice for corned beef hash.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Return the corned beef cooking liquid to a boil over medium-high heat. (If starting with new cooking liquid, combine the chicken broth, water, chopped carrots, celery, and onion in a large pot and bring to a boil.)  </li><br/>",
                 "<li class='animated fadeInLeft'>  Once the cooking liquid is boiling, add the potatoes and cook for 10 minutes, until half-cooked. Add the halved carrots and cabbage, cover, and cook for 10–15 minutes more, until the vegetables are tender.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Transfer the vegetables to a serving platter with the sliced brisket and ladle the cooking liquid over.  </li><br/>",
                 "<li class='animated fadeInLeft'>  Enjoy!  </li><br/>",
                 ]
 },
];